name: YouTube Summarizer Jarred Younger, PhD

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger
  #   inputs:
  #     max_summaries:
  #       description: 'Maximum number of summaries to generate'
  #       required: false
  #       default: '5'
  #       type: string

jobs:
  summarize:
    # Only run on branches that start with 'channel-'
    if: startsWith(github.ref_name, 'channel-')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        # Checkout the branch that contains summary files for this channel
        ref: channel-jarred-younger-phd
        # Fetch full history to ensure we can commit
        fetch-depth: 0
        # Use a token that can push to protected branches if needed
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Run YouTube Summarizer
      env:
        CHANNEL_ID : 'UCoVoOvIX90IMEZCbBf_ycEA'  # Jarred Younger, PhD channel ID
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: |
        python youtube_summarizer.py "$CHANNEL_ID" "$RECIPIENT_EMAIL" --git-commits-on